name: grafana-stack

version: "3.8"
services:
  grafana:
    hostname: grafana
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - '3000:3000'
  prometheus:
    hostname: prometheus
    image: prom/prometheus
    container_name: prometheus
    restart: always
    environment:
      - ENABLE_FEATURE=otlp-write-receiver
    ports:
      - '9090:9090'
    volumes:
      - prometheus:/etc/prometheus
  local-sql-server:
      hostname: local-host-sql
      container_name: local-sql-server
      restart: always
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
        - '1433:1433'
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Aa123456
  loki:
    image: grafana/loki:3.0.0
    hostname: loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki:/mnt/config
    command:
      - "-config.file=/mnt/config/loki-config.yaml"
volumes:
  grafana:
  prometheus:
  loki: